#!/bin/bash

## (C) 2021
## Ramon Brooker
## rbrooker@aeo3.io

## Aliases

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

if [ $UID = 0 ]; then
    ## For Root User
    alias passwd='printf "\n ${RED}${BOLD}Never${NC} create a password for ${RED}ROOT \n\n" '
fi
# sudo hint
if [ ! -e "$HOME/.sudo_as_admin_successful" ] && [ ! -e "$HOME/.hushlogin" ] ; then
    case " $(groups) " in *\ qe-admin\ *|*\ sudo\ *)
    if [ -x /usr/bin/sudo ]; then
cat <<-EOF
	To run a command as administrator (user "root"), use "sudo <command>".
	See "man sudo_root" for details.

EOF
    fi
    esac
fi

# Aliases that ALTER standard commands

# enable colour support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then

    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

# Add Colour to Grep
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'

    # some more ls aliases
    alias ls='ls --color=auto'
    alias ll='ls -alhF --color=auto'
    alias la='ls -A --color=auto'
    alias l='ls -CF  --color=auto'
    alias l.='ls -d .* --color=auto'
fi

alias df='df -HT'
alias vi='vim'


# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

## Quick Add

alias local-user-change='vim ${HOME}/.over-ride; source ${HOME}/.bashrc'
alias rebash='source ${HOME}/.bashrc '

## Navigation and Laziness
alias ..='cd ../'
alias x='exit'

alias histawk='history | awk '

## Cause I usually can't remember
alias clean='clear'
alias gtar='tar -cvzf '
alias v='vim '
## rsync -a ==> -rlptgoD ==> --recursive --links --perms --times --group --owner --devices
alias rsync-dir='rsync -a --human-readable --progress --compress '

## Just for standard Users
if [[ ${UID} -gt 999 ]]; then
    alias su='sudo su '
fi
## Navigation Laziness
    alias opt='cd /opt'


## System Tools
alias psgrep='ps aux | grep -v grep | grep '
alias established='netstat -napt | grep ESTABLISHED'
alias listening='netstat -napt | grep LISTEN'
alias get-timewait='ss | grep TIME_WAIT | wc -l'
alias llistening='sudo netstat -napt | grep -i LISTEN | grep 127.0.0.1'
alias changlog-date='date +"%a %b %d %Y"'

## Update bootstap config
alias kickit='cd /etc/custom/configuration/; git status ; git pull '