#!/bin/bash

## Custom DISPLAY Setting 
# export DISPLAY=

# export VAR=VALUE
## PS Colour System Specific --  Default   
## PS_SQUARE_BRACKETS='\[\033[38;5;242m\]'
## PS_HOSTNAME_COLOUR='\[\033[38;5;29m\]'
## PS_USERNAME_COLOUR='\[\033[38;5;2m\]'
## PS_PATH='\[\033[38;5;37m]'
## PS_PROMPT='\[\033[38;5;37m\]'

